export const cars = [
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
  {
    model: 'Porsche 911',
    type: 'Coupe',
    carsNumber: 5,
    personNumber: 2,
    price: '200',
  },
];
